package servlet;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;

import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import bean.ApplicationBean;
import bean.EmployeeBean;
import dao.ApplicationDAO;

/**
 * Servlet implementation class ApplicationServlet
 */
@WebServlet("/ApplicationServlet")
public class ApplicationServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		    HttpSession session = request.getSession();
	        EmployeeBean employee = (EmployeeBean) session.getAttribute("empBean");
	        
	        if (employee == null) {
	        	session.setAttribute("eMsg", "error : session timeout");
	            response.sendRedirect(request.getContextPath() + "/index.jsp");
	            return;
	        }

	        String employeeId = employee.getEmp_id();

	        ApplicationDAO dao = new ApplicationDAO();
	        EmployeeBean emp = dao.selectEmployee(employeeId);
	        String dptName = "未所属";

	        if (employee != null) {
	            dptName = dao.selectDepartmentName(employee.getDpt_id());
	        }

	        request.setAttribute("employeeInfo", employee);
	        request.setAttribute("departmentName", dptName);
	        RequestDispatcher rd = request.getRequestDispatcher("/WEB-INF/jsp/application.jsp");
	        rd.forward(request, response);
	}


	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// 文字化け防止のためのエンコーディング設定
		request.setCharacterEncoding("UTF-8");

		try {
			// 1. ログイン状態の確認
			HttpSession session = request.getSession();
			EmployeeBean employee = (EmployeeBean) session.getAttribute("empBean");
			
			if (employee == null) {
				response.setStatus(HttpServletResponse.SC_UNAUTHORIZED); // 401
				return;
			}

			// 2. リクエストパラメータの取得
			String employeeId = employee.getEmp_id();
			String applicationType = request.getParameter("applicationType");
			String paymentMethod   = request.getParameter("paymentMethod");
			String amountParam     = request.getParameter("amount");
			String content         = request.getParameter("content");
			String reason          = request.getParameter("reason");
			String note            = request.getParameter("note");
			String urgentFlagParam = request.getParameter("urgentFlag");

			// 3. 数値データの型変換
			int amount = 0;
			if (amountParam != null && !amountParam.trim().isEmpty()) {
				amount = Integer.parseInt(amountParam.trim());
			}

			// 4. 上限金額マスタの確認
			ApplicationDAO dao = new ApplicationDAO();
			Integer posAmount = dao.selectPositionAmount(employee.getPos_id());

			// 5. 金額バリデーションチェック
			if (posAmount != null && amount > posAmount) {
				response.setContentType("text/plain; charset=UTF-8");
				response.setStatus(HttpServletResponse.SC_BAD_REQUEST); // 400 エラー
				response.getWriter().write("申請金額が役職の上限（" + posAmount + "円）を超えています。");
				return;
			}

			// 6. 主キー(申請ID)の自動採番
			String timeStamp = new SimpleDateFormat("yyMMddHHmmssSSS").format(new Date());
			String autoGeneratedId = "AP" + timeStamp;

			// 7. 緊急フラグの文字列変換
			String urgentStr = "通常";
			if (urgentFlagParam != null) {
				String u = urgentFlagParam.trim().toLowerCase();
				if ("on".equals(u) || "true".equals(u) || "1".equals(u)) {
					urgentStr = "緊急";
				}
			}

			// 8. 作成日時の取得
			LocalDateTime now = LocalDateTime.now();

			// 9. 登録用Beanオブジェクトの組み立て
			ApplicationBean bean = new ApplicationBean();
			bean.setApctId(autoGeneratedId);
			bean.setEmployeeId(employeeId);
			bean.setContent(content);
			bean.setType(applicationType);
			bean.setPaymentMethod(paymentMethod);
			bean.setAmount(amount);
			bean.setReason(reason);
			bean.setNote(note);
			bean.setUrgent(urgentStr);
			bean.setStatus_id(1); 
			bean.setCreateDate(now);
			bean.setUpdateDate(now);
			bean.setDeleted(false);

			// 10. データベースへの登録実行
			int result = dao.insert(bean);

			// 11. 結果の返却
			if (result > 0) {
				response.setContentType("text/plain; charset=UTF-8");
				response.setStatus(HttpServletResponse.SC_OK); // 200 OK
				response.getWriter().write("success");
			} else {
				response.setContentType("text/plain; charset=UTF-8");
				response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR); // 500
				response.getWriter().write("データベースの登録に失敗しました。");
			}

		} catch (Exception e) {
			log("ApplicationServlet error", e);
			
			response.setContentType("text/plain; charset=UTF-8");
			response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR); // 500 エラー
			response.getWriter().write("システムエラーが発生しました。詳細: " + e.getMessage());
		}
	}
}