package servlet;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import bean.ApplicationBean;
import bean.EmployeeBean;
import dao.ApplicationDAO;

@WebServlet("/Application")
public class ApplicationServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        HttpSession session = request.getSession();
        String employeeId = (String) session.getAttribute("emp_id");
        
        if (employeeId == null) {
            response.sendRedirect(request.getContextPath() + "/login_mock.jsp");
            return;
        }

        ApplicationDAO dao = new ApplicationDAO();
        EmployeeBean employee = dao.selectEmployee(employeeId);
        String dptName = "未所属";

        if (employee != null) {
            dptName = dao.selectDepartmentName(employee.getDpt_id());
        }

        request.setAttribute("employeeInfo", employee);
        request.setAttribute("departmentName", dptName);

        request.getRequestDispatcher("/application.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");

        try {
            HttpSession session = request.getSession();
            String employeeId = (String) session.getAttribute("emp_id");
            
            if (employeeId == null) {
                response.sendRedirect(request.getContextPath() + "/login_mock.jsp");
                return;
            }

            String applicationType = request.getParameter("applicationType");
            String paymentMethod   = request.getParameter("paymentMethod");
            String amountParam     = request.getParameter("amount");
            String content         = request.getParameter("content");
            String reason          = request.getParameter("reason");
            String note            = request.getParameter("note");
            String urgentFlagParam = request.getParameter("urgentFlag");

            int amount = 0;
            if (amountParam != null && !amountParam.trim().isEmpty()) {
                amount = Integer.parseInt(amountParam.trim());
            }

            // 主キー(apct_id)をサーブレット側で生成
            String timeStamp = new SimpleDateFormat("yyMMddHHmmssSSS").format(new Date());
            String autoGeneratedId = "AP" + timeStamp;

            // 緊急フラグの文字列変換
            String urgentStr = "通常";
            if (urgentFlagParam != null) {
                String u = urgentFlagParam.trim().toLowerCase();
                if ("on".equals(u) || "true".equals(u) || "1".equals(u)) {
                    urgentStr = "緊急";
                }
            }

            // 現在日時の取得
            LocalDateTime now = LocalDateTime.now();

            // 新しい網羅版 ApplicationBean にデータを格納
            ApplicationBean bean = new ApplicationBean();
            bean.setApctId(autoGeneratedId);          // 申請ID
            bean.setEmployeeId(employeeId);           // 社員ID
            bean.setContent(content);                 // 申請内容
            bean.setType(applicationType);            // 申請種別
            bean.setPaymentMethod(paymentMethod);     // 精算方式
            bean.setAmount(amount);                   // 申請金額
            bean.setReason(reason);                   // 申請理由
            bean.setNote(note);                       // 備考(remark)
            bean.setUrgent(urgentStr);                // 緊急度
            bean.setStatus("申請中");                 // 申請状態の初期値
            bean.setCreateDate(now);                  // 作成時間
            bean.setUpdateDate(now);                  // 変更時間
            bean.setDeleted(false);                   // 削除フラグ

            ApplicationDAO dao = new ApplicationDAO();
            dao.insert(bean);

            request.getRequestDispatcher("/app_submit.jsp").forward(request, response);

        } catch (Exception e) {
            log("ApplicationServlet error", e);
            
            try {
                HttpSession session = request.getSession();
                String employeeId = (String) session.getAttribute("emp_id");
                
                if (employeeId != null) {
                    ApplicationDAO dao = new ApplicationDAO();
                    EmployeeBean employee = dao.selectEmployee(employeeId);
                    String dptName = "未所属";
                    if (employee != null) {
                        dptName = dao.selectDepartmentName(employee.getDpt_id());
                    }
                    request.setAttribute("employeeInfo", employee);
                    request.setAttribute("departmentName", dptName);
                }
                
                request.setAttribute("errorMessage", "申請の登録中にエラーが発生しました。");
                request.getRequestDispatcher("/application.jsp").forward(request, response);
                
            } catch (Exception ex) {
                log("Fatal error in catch block", ex);
            }
        }
    }
}