package servlet;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import bean.ApplicationBean;
import bean.EmployeeBean;
import dao.ApplicationDAO;

@WebServlet("/Application")
public class ApplicationServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        HttpSession session = request.getSession();
        EmployeeBean employee = (EmployeeBean) session.getAttribute("loginEmployee");
        
        if (employee == null) {
            response.sendRedirect(request.getContextPath() + "/login_mock.jsp");
            return;
        }

        ApplicationDAO dao = new ApplicationDAO();
        String dptName = dao.selectDepartmentName(employee.getDpt_id());

        request.setAttribute("employeeInfo", employee);
        request.setAttribute("departmentName", dptName);

        request.getRequestDispatcher("/application.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setCharacterEncoding("UTF-8");

        try {
            HttpSession session = request.getSession();
            EmployeeBean employee = (EmployeeBean) session.getAttribute("loginEmployee");
            
            if (employee == null) {
                response.sendRedirect(request.getContextPath() + "/login_mock.jsp");
                return;
            }

            String employeeId = employee.getEmp_id();
            String applicationType = request.getParameter("applicationType");
            String paymentMethod   = request.getParameter("paymentMethod");
            String amountParam     = request.getParameter("amount");
            String content         = request.getParameter("content");
            String reason          = request.getParameter("reason");
            String note            = request.getParameter("note");
            String urgentFlagParam = request.getParameter("urgentFlag");

            int amount = 0;
            if (amountParam != null && !amountParam.trim().isEmpty()) {
                amount = Integer.parseInt(amountParam.trim());
            }

            String timeStamp = new SimpleDateFormat("yyMMddHHmmssSSS").format(new Date());
            String autoGeneratedId = "AP" + timeStamp;

            String urgentStr = "通常";
            if (urgentFlagParam != null) {
                String u = urgentFlagParam.trim().toLowerCase();
                if ("on".equals(u) || "true".equals(u) || "1".equals(u)) {
                    urgentStr = "緊急";
                }
            }

            LocalDateTime now = LocalDateTime.now();

            int initialStatusId = 1;
            if ("E04".equals(employee.getPos_id())) {
                initialStatusId = 2;
            }

            // 無引数コンストラクタで生成しているため、フィールドが追加されてもこの記述で動作します
            ApplicationBean bean = new ApplicationBean();
            bean.setApctId(autoGeneratedId);
            bean.setEmployeeId(employeeId);
            bean.setContent(content);
            bean.setType(applicationType);
            bean.setPaymentMethod(paymentMethod);
            bean.setAmount(amount);
            bean.setReason(reason);
            bean.setNote(note);
            bean.setUrgent(urgentStr);
            bean.setStatus_id(initialStatusId);
            bean.setCreateDate(now);
            bean.setUpdateDate(now);
            bean.setDeleted(false);

            ApplicationDAO dao = new ApplicationDAO();
            dao.insert(bean);

            request.getRequestDispatcher("/app_submit.jsp").forward(request, response);

        } catch (Exception e) {
            log("ApplicationServlet error", e);
            
            try {
                // エラー時の再表示処理
                HttpSession session = request.getSession();
                EmployeeBean employee = (EmployeeBean) session.getAttribute("loginEmployee");
                
                if (employee != null) {
                    ApplicationDAO dao = new ApplicationDAO();
                    String dptName = dao.selectDepartmentName(employee.getDpt_id());
                    
                    request.setAttribute("employeeInfo", employee);
                    request.setAttribute("departmentName", dptName);
                }
                
                request.setAttribute("errorMessage", "申請の登録中にエラーが発生しました。");
                request.getRequestDispatcher("/application.jsp").forward(request, response);
                
            } catch (Exception ex) {
                log("Fatal error in catch block", ex);
            }
        }
    }
}