package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

import bean.ApplicationBean;
import bean.EmployeeBean;

public class ApplicationDAO extends DAO {

	public int insert(ApplicationBean bean) {
		Connection con = dbConnect();
		int result = 0;
		
		String timeStamp = new SimpleDateFormat("yyMMddHHmmssSSS").format(new Date());
		String autoGeneratedId = "AP" + timeStamp;
		
		String sql = "INSERT INTO applications (apct_id, emp_id, content, type, method, amount, reason, remark, urgent, status, create_date, update_date, is_deleted) "
				+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)";
				
		try {
			if(con != null) {
				PreparedStatement st = con.prepareStatement(sql);
				
				st.setString(1, autoGeneratedId);
				st.setString(2, bean.getEmployeeId());
				st.setString(3, bean.getContent());
				st.setString(4, bean.getType());
				st.setString(5, bean.getPaymentMethod());
				st.setInt(6, bean.getAmount()); 
				st.setString(7, bean.getReason());
				st.setString(8, bean.getNote());
				st.setString(9, bean.isUrgent() ? "緊急" : "通常");
				st.setString(10, "申請中");
				
				Timestamp now = new Timestamp(System.currentTimeMillis());
				st.setTimestamp(11, now);
				st.setTimestamp(12, now);

				result = st.executeUpdate();
			}
		} catch(SQLException e) {
			System.out.println("insertエラー");
			System.out.println(e.getMessage());
		}
		
		dbClose(con);
		return result;
	}

	/**
	 * 社員IDを基に、指定されたEmployeeBeanを取得する
	 */
	public EmployeeBean selectEmployee(String empId) {
		Connection con = dbConnect();
		PreparedStatement st = null;
		ResultSet rs = null;
		EmployeeBean employee = null;

		String sql = "SELECT emp_id, emp_name, email, dpt_id, pos_id, is_deleted FROM employees WHERE emp_id = ? AND is_deleted = 0";

		try {
			if (con != null) {
				st = con.prepareStatement(sql);
				st.setString(1, empId);
				rs = st.executeQuery();

				if (rs.next()) {
					employee = new EmployeeBean();
					employee.setEmp_id(rs.getString("emp_id"));
					employee.setEmp_name(rs.getString("emp_name"));
					employee.setEmail(rs.getString("email"));
					employee.setDpt_id(rs.getString("dpt_id"));
					employee.setPos_id(rs.getString("pos_id"));
					employee.setIs_deleted(rs.getBoolean("is_deleted"));
				}
			}
		} catch (SQLException e) {
			System.out.println("selectEmployeeエラー");
			System.out.println(e.getMessage());
		} finally {
			if (rs != null) try { rs.close(); } catch (SQLException e) {}
			if (st != null) try { st.close(); } catch (SQLException e) {}
			dbClose(con);
		}
		return employee;
	}

	/**
	 * 部署IDを基に、部署名を取得する
	 */
	public String selectDepartmentName(String dptId) {
		Connection con = dbConnect();
		PreparedStatement st = null;
		ResultSet rs = null;
		String dptName = "未所属";

		String sql = "SELECT dpt_name FROM departments WHERE dpt_id = ?";

		try {
			if (con != null) {
				st = con.prepareStatement(sql);
				st.setString(1, dptId);
				rs = st.executeQuery();

				if (rs.next()) {
					dptName = rs.getString("dpt_name");
				}
			}
		} catch (SQLException e) {
			System.out.println("selectDepartmentNameエラー");
			System.out.println(e.getMessage());
		} finally {
			if (rs != null) try { rs.close(); } catch (SQLException e) {}
			if (st != null) try { st.close(); } catch (SQLException e) {}
			dbClose(con);
		}
		return dptName;
	}
}