package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

import bean.ApplicationBean;

public class ApplicationDAO extends DAO {
	public int insert(ApplicationBean bean) {
		Connection con = dbConnect();
		int result = 0;
		
		// 主キー(apct_id)を自動生成
		String timeStamp = new SimpleDateFormat("yyMMddHHmmssSSS").format(new Date());
		String autoGeneratedId = "AP" + timeStamp;
		
		// スキーマに合わせた13カラムのINSERT文
		String sql = "INSERT INTO applications (apct_id, emp_id, content, type, method, amount, reason, remark, urgent, status, create_date, update_date, is_deleted) "
				+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)";
				
		try {
			if(con != null) {
				PreparedStatement st = con.prepareStatement(sql);
				
				st.setString(1, autoGeneratedId);
				st.setString(2, bean.getEmployeeId());
				st.setString(3, bean.getContent());
				st.setString(4, bean.getType());
				st.setString(5, bean.getPaymentMethod());
				st.setInt(6, bean.getAmount()); 
				st.setString(7, bean.getReason());
				st.setString(8, bean.getNote());        // remark
				st.setString(9, bean.isUrgent() ? "緊急" : "通常");
				st.setString(10, "申請中");             // statusの初期値
				
				// 日時処理
				Timestamp now = new Timestamp(System.currentTimeMillis());
				st.setTimestamp(11, now); // create_date
				st.setTimestamp(12, now); // update_date

				result = st.executeUpdate();
			}
		} catch(SQLException e) {
			System.out.println("insertエラー");
			System.out.println(e.getMessage());
		}
		
		dbClose(con);
		return result;
	}
}